### ISSUE TITLE
PyTorch env file

### ISSUE THREAD

**Issue by hugobowne** [coiled/coiled-resources#1]
[this NB](https://github.com/coiled/coiled-resources/blob/master/analyzing-microscopy-images-with-pytorch-and-dask/dask-pytorch.ipynb) says do this

`conda env create -f environment_pytorch-example.yml`

but the env in the repo has a different name 

@pavithraes

**Comment by hugobowne** [comment]
it's also probably worth giving the environment a name as conda throws me an error currently.


e.g.

```
name: pytorch-dask
channels:
  - conda-forge
dependencies:
  - coiled
  - dask=2021.5.1
  - pytorch=1.8.0
  - pytorch-cpu=1.6.0
  - torchvision=0.9.0
  - matplotlib=3.3.2
```

**Comment by hugobowne** [comment]
hmmm also looks like the env doesn't have jupyter so after activating I can't open NB

I'll happily make a PR here but would like @pavithraes' thoughts 1st

**Comment by hugobowne** [comment]
the data is also on google drive so we may want to put it on s3

**Comment by hugobowne** [comment]
the rest of the NB ran smoothly for me

**Comment by pavithraes** [comment]
@hugobowne As discussed earlier, we've updated the env file, but we're not changing the data location for now. :) PR is merged, so closing this issue!
